steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME-octopus:$COMMIT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME-octopus:$COMMIT_SHA"]
timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_32'
