[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = '2018'
name = 'pallet-template'
version = "3.0.0"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { default-features = false, version = "3.0.0", path = "../../../../frame/support" }
frame-system = { default-features = false,  version = "3.0.0",  path = "../../../../frame/system" }
frame-benchmarking = { default-features = false,  version = "3.1.0",  path = "../../../../frame/benchmarking", optional = true }

getrandom = { version = "0.2.3",  default-features = false, features = ["js"] }
serde = { version = "1.0.125", default-features = false }
serde_json = { version = "1.0.65", default-features = false, features = ["alloc"] }
ics23 = { version = "0.6.5",  default-features = false , git = "https://github.com/DaviRain-Su/ics23.git", branch = "dv-tryinto-error" }
regex = "1.5.4"

#tonic = { version = "0.4.1", default-features = false }
#socket2 = { version = "0.4.1", default-features = false }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-core = { default-features = false, version = "3.0.0", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "3.0.0", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "3.0.0", path = "../../../../primitives/runtime" }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	"serde/std",
	"serde_json/std",
	"ics23/std",
	"regex/std",
	"getrandom/std",
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
